
@baseUrl = http://16.24.105.9/api


### Login request
### Step 1: Get access token
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "user@example.com",
    "password": "user"
}


### Get Ladies Night event
# @name getLadiesNightEvent
GET   {{baseUrl}}/events/5e3b7f1c-2d4a-4f6e-9a8b-1c2d3e4f5a6b
Content-Type: application/json
Authorization: Bearer {{login.response.body.accessToken}}



### Update Ladies Night
# @name updateLadiesNightEvent
PATCH     {{baseUrl}}/events/5e3b7f1c-2d4a-4f6e-9a8b-1c2d3e4f5a6b
Content-Type: application/json
Authorization: Bearer {{login.response.body.accessToken}}


{
  "id": "5e3b7f1c-2d4a-4f6e-9a8b-1c2d3e4f5a6b",
  "name": "Ladies Night",
  "type": "WEEKLY",
  "description": "Ladies Night",
  "startDate": null,
  "endDate": null,
  "cronStartDate": "01 17 * * 1",
  "cronEndDate": "07 17 * * 1",
  "thumbnailKey": "events/ladies-night-wallpaper.jpg",
  "videoKey": "events/volto-brunch-1.mp4"
}



### Get Event By Id
# @name getEvent
GET     {{baseUrl}}/events/b6d1e3f4-5a7c-4f2b-8e1a-9c3b2d4f5a6e
Content-Type: application/json
Authorization: Bearer {{login.response.body.accessToken}}




### Get All Events
# @name getEvents
GET     {{baseUrl}}/events?eventType=WEEKLY
Content-Type: application/json
Authorization: Bearer {{login.response.body.accessToken}}
