

@baseUrl = http://localhost:3000/api



############################
### Register a new user
# @name register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "username":"test",
    "email":"test@test.test",
    "phoneNumber":"80000000",
    "gender":"M",
    "password":"123456"
}



### Login request
### Step 1: Get access token
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "user@example.com",
    "password": "user"
}


### Get presigned url for the thumbnail
# @name getPresignedUrl
POST {{baseUrl}}/media/presigned-url
Content-Type: application/json
Authorization: Bearer {{login.response.body.accessToken}}

{
    "mimeType": "image/jpeg",
    "fileSize": 136877,
    "fileType": ".jpg",
    "originalName": "img.jpg",
    "entityType": "EVENT",
    "mediaPurpose": "thumbnail"
}

 
### Get presigned url for the video
# @name getPresignedUrl2
POST {{baseUrl}}/media/presigned-url
Content-Type: application/json
Authorization: Bearer {{login.response.body.accessToken}}

{
    "mimeType": "image/jpeg",
    "fileSize": 136877,
    "fileType": ".jpg",
    "originalName": "img.jpg",
    "entityType": "EVENT",
    "mediaPurpose": "video"
}


### Upload the thumbnail into S3
# @name uploadFile
PUT {{getPresignedUrl.response.body.url}}
Content-Type: image/jpeg

< ./assets/img.jpg



### Register the video into S3
# @name uploadFile
PUT {{getPresignedUrl2.response.body.url}}
Content-Type: image/jpeg

< ./assets/img.jpg



### Create Event
# @name createEvent
POST  {{baseUrl}}/events
Content-Type: application/json
Authorization: Bearer {{login.response.body.accessToken}}

{
    "name": "Ladies Night",
    "type": "WEEKLY",
    "description": "This is a test event for ladies night",
    "startDate": null,
    "endDate": null,
    "cronStartDate" : "",
    "cronEndDate":"",
    "thumbnailKey": "{{getPresignedUrl.response.body.s3Key}}",
    "videoKey": "{{getPresignedUrl2.response.body.s3Key}}"
}





### Check the event created
# @name getEvent
GET   {{baseUrl}}/events/{{createEvent.response.body.id}}
Content-Type: application/json
Authorization: Bearer {{login.response.body.accessToken}}




