
@baseUrl = http://localhost:3000/api



### Login request
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "superadmin@example.com",
    "password": "superadmin"
}



### Get SpinningWheel Instance As Admin
# @name getSpinnigWheelInstance
GET      {{baseUrl}}/spinning-wheel/admin/instance
Content-Type: application/json
Authorization: Bearer {{login.response.body.accessToken}}




### Get One Wheel Reward
# @name updateWheelRewards
PATCH       {{baseUrl}}/spinning-wheel/admin/instance
Content-Type: application/json
Authorization: Bearer {{login.response.body.accessToken}}


{
    "id": "{{getSpinnigWheelInstance.response.body.id}}",
    "name":"Spinning Wheel Name Updated",
    "startDate": "2025-09-12T11:35:10.161Z",
    "endDate": "2025-09-12T11:38:10.161Z",
    "rewardList":[
        {
            "id": "{{getSpinnigWheelInstance.response.body.rewardList[0].id}}",
            "name": "Reward 1 updated from Rest Client"
        },
          {
            "id": "{{getSpinnigWheelInstance.response.body.rewardList[1].id}}",
            "name": "Reward 2 updated from Rest Client"
        },
          {
            "id": "{{getSpinnigWheelInstance.response.body.rewardList[2].id}}",
            "name": "Reward 3 updated from Rest Client"
        },
          {
            "id": "{{getSpinnigWheelInstance.response.body.rewardList[3].id}}",
            "name": "Reward 4 updated from Rest Client"
        },
          {
            "id": "{{getSpinnigWheelInstance.response.body.rewardList[4].id}}",
            "name": "Reward 5555 updated from Rest Client"
        }
    ]
}




### Is SpinningWheel Available
# @name getSpinnigWheel
GET      {{baseUrl}}/spinning-wheel/
Content-Type: application/json
Authorization: Bearer {{login.response.body.accessToken}}


### Get Wheel Rewards
# @name getWheelRewards
GET      {{baseUrl}}/spinning-wheel-reward/
Content-Type: application/json
Authorization: Bearer {{login.response.body.accessToken}}



### Get One Wheel Reward
# @name updateWheelRewards
PATCH       {{baseUrl}}/spinning-wheel-reward/
Content-Type: application/json
Authorization: Bearer {{login.response.body.accessToken}}


{
    "rewards":[
        {
            "id": "{{getWheelRewards.response.body.rewardsList[0].id}}",
            "name": "Reward 1 updated from Rest Client"
        },
          {
            "id": "{{getWheelRewards.response.body.rewardsList[1].id}}",
            "name": "Reward 2 updated from Rest Client"
        },
          {
            "id": "{{getWheelRewards.response.body.rewardsList[2].id}}",
            "name": "Reward 3 updated from Rest Client"
        },
          {
            "id": "{{getWheelRewards.response.body.rewardsList[3].id}}",
            "name": "Reward 4 updated from Rest Client"
        },
          {
            "id": "{{getWheelRewards.response.body.rewardsList[4].id}}",
            "name": "Rbe7t l 3asba"
        }
    ]
}


### Get User SpinnigWheel Quota
# @name getUserSpinningWheelQuota
GET      {{baseUrl}}/spinning-wheel/get-quota
Content-Type: application/json
Authorization: Bearer {{login.response.body.accessToken}}




### Generate user code of a reward
# @name generateRewardCode
POST      {{baseUrl}}/spinning-wheel/generate-code
Content-Type: application/json
Authorization: Bearer {{login.response.body.accessToken}}

{
  "wheelRewardId" :"{{getWheelRewards.response.body.rewardsList[4].id}}"
}




### Redeem User Code (Waiter Role)
# @name generateRewardCode
POST      {{baseUrl}}/spinning-wheel/redeem-code
Content-Type: application/json
Authorization: Bearer {{login.response.body.accessToken}}

{
  "code" :"{{getUserSpinningWheelQuota.response.body.code}}"
}


